server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

jwt:
  secret: smop-secret-key-1234567890
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.smop: DEBUG
