apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app: smop
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: authentication
