server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

websocket:
  broker:
    prefix: /topic
    app-prefix: /app

logging:
  level:
    com.smop: DEBUG
